defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  pool: 5
  host: localhost

test: &test
  <<: *defaults
  database: selenium_rails_test

development:
  <<: *defaults
  database: selenium_rails

cucumber:
  <<: *test
